title : 문어복어 기술 블로그
name: '문어복어 기술 블로그'
description: '문어복어의 기술 블로그입니다. 느리지만 꾸준히 합니다.'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'
  - url: '#'
    title: 'Featured post #3'

collections:
  springs:
    title: Spring
    default_open: false
    output: true
  tils:
    title: TIL
    default_open: false
    output: true
  os:
    title: OS
    default_open: false
    output: true
  javas:
    title: JAVA
    default_open: false
    output: true

defaults:
  - scope:
      type: javas
    values:
      title: JAVA
      permalink: /JAVA/:title
  - scope:
      type: tils
    values:
      title: TIL
      permalink: /TIL/:title
  - scope:
      type: springs
    values:
      title: Spring
      permalink: /spring/:title
  - scope:
       type: os
    values:
      title: OS
      permalink: /os/:title

plugins:
  - jekyll-sitemap
